global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'recommendation_service'
    static_configs:
      - targets: ['recommendation_service:8000']

  - job_name: 'event_collector'
    static_configs:
      - targets: ['event_collector:8000']
